### ISSUE TITLE
Figure out how to improve the document within the repo

### ISSUE THREAD

**Issue by djplaner** [djplaner/Card-Interface-Tweak#17]
Need better docs.

There are some reasonable ones produced in the Content Interface on L@G. Need to convert that into something that can be used by other people by including it into the repo.

**Comment by djplaner** [comment]
## To do

- [ ] What practices exist with docs in github projects
    - [ ] is it just Markdown? Can it host HTML?
    - [ ] What options exist to style that HTML?
    - [ ] How to convert Word docs automagically to that format?
- [ ] Implement the process

**Comment by djplaner** [comment]
## Options for documenting github projects

### [Github guide - documeting your projects](https://guides.github.com/features/wikis/)

Three options

1. README
2. Wikis
3. GitHub pages

#### Wikis

- uses [GitHub markup](https://github.com/github/markup)
- supports [various markups](https://github.com/github/markup#markups)

Markdown seems to be the best connection

#### [GitHub pages](https://pages.github.com/)

## [MkDocs](https://www.mkdocs.org/)

Static site generator aimed at project documentation - Markdown.  YAML configuration.  Can be hosted anywhere.  Python

[Custom themes](https://github.com/mkdocs/mkdocs/wiki/MkDocs-Themes)

[Automated deploy to GitHub pages](https://www.mkdocs.org/user-guide/deploying-your-docs/)

**Seems mkdocs and github pages is the way to go**

**Comment by djplaner** [comment]
## Trying out mkdocs

[Instructions](https://romandc.com/techtalk-mkdocs/)

[And we're done](https://djplaner.github.io/Card-Interface-Tweak/)

**Comment by djplaner** [comment]
## Tasks to do

### mkdocs

- [ ] Fix styling of the first row of the before/after table on docs home page
- [ ] Figure out and use permalinks for headings in docs

### Converting word docs

- [ ] Convert title (invisble) to H1
- [ ] Convert H1 to H2 etc.
- [ ] Add gu_study style mapping to Python mammoth
- [ ] install python mammoth on windows
- [ ] Identify what extra conversions need to be done to "de-Griffith" docs

### Tweak code

- [ ] Add way to switch document links when not on a Griffith site

**Comment by djplaner** [comment]
## newModern branch

Starting with webpack. 

- [ ] Analyse what Card Interface 
- [ ] Plan move to modules and dropping jQuery

**Comment by djplaner** [comment]
## Analysis

cardsInterface current steps
- Blackboard patterns
- get page id (Blackboard)
- Documentation
- calculate the term/year
- find the card interface item
- **getCardItems**
- **addCardInterface**
- update card click event listeners
- Make cards clickable
- hide images
- remove the item icons

### getCardItems

- get al the content items that specify cards
- extractCardsFromContent
    - loop thru each card
        - getReviewStatus
        - handle vtbgenerated
        - extractCardMetaData
        - and essentially construct the items
        - 

-
