### ISSUE TITLE
Card coming soon meta data

### ISSUE THREAD

**Issue by djplaner** [djplaner/Card-Interface-Tweak#26]
FYI, new card feature idea that's come up - Card Coming Soon: week 3 - which would add a differently styled date element to the top left of a card. e.g. Available Mar 21. If it's before the specified date.
 
For the situation where course content is being finalised during trimester. So don't want students clicking into to see nothing of use.  However, rather than just hide the card. The desire is to have the card there so the student can see the shape of the trimester.

**Comment by djplaner** [comment]
### Refined initial design
	
1. [ ] Yellow background message at bottom of card (e.g. [these](https://d2gdtie5ivbdow.cloudfront.net/media/user/images/user_tailwind_cards.png))
2. [ ] Replace the download icon with 🚧  and have some text with the three components: date, date label, and message label.
3. [ ]If the coming soon date has passed, no message at the bottom.
4. [ ] If "edit mode" on,  there was also a short pointer to the documentation explaining "how to turn off coming soon"?  
5. [ ] Add a "noComingSoon" parameter to the "Card Interface" item. Which would automatically turn off all coming soon on the page. Meaning you wouldn't have to remove the entries from each card.

**Comment by djplaner** [comment]
## Extract the card meta data

1. Add entry to CARD_META_DATA_FIELDS

## Handle the card meta data - data calculations

1. [ ] Add handler to switch
2. [ ] Write the function (maybe just use handleCardDate)
3. [ ] add it to the card interface

## Decide what it should look like

See above

## Add support in the template

1. [ ] Add ```{COMING_SOON}``` to the standard templates
2. [ ] Add HTML for the ```comingSoonHtmlTemplate``` for the different standard templates

## Update the display of the card

- [ ] Update addCardInterface

**Comment by djplaner** [comment]
Testing

- [ ] hiding container list (not currently turned on, also failing horribly)
- [ ] before all comingSoon
- [ ] after some
- [ ] after all
- [ ] noComingSoon
- [ ] No use of coming soon at all
