### ISSUE TITLE
Componentize branch - planning and testing

### ISSUE THREAD

**Issue by djplaner** [djplaner/Card-Interface-Tweak#46]
Leave behind the mess of jQuery and 00s Javascript with a new design that
1. [ ] Uses web components and contemporary JS to provide a flexible, platform independent tool
2. [ ] Can work with the existing tweak code (i.e. not require changes)

## Tasks

- [ ] Plan initial operation
- [ ] Test it
- [ ] Plan conversion - including analysis of Card Interface

**Comment by djplaner** [comment]
## Plan A

Tweak code stays the same 
- include content.js
- call cardsInterface

Transform cardsInterface into
- add a web component to the Card Interface item
- use a Javascript object to create the Card Interface data structure
    - Eventually this becomes a factory that detects the context of the page and uses the correct data model
- Pass it to the component (perhaps as singleton)

Question is whether we can include the components in the Javascript - perhaps having to change the tweak code
